[project]
name = "rag-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.0.15",
    "openai>=1.93.0",
    "rich>=14.0.0",
    "streamlit>=1.46.1",
]

[dependency-groups]
dev = [
    "ruff>=0.12.3",
]
